ALTER TABLE "CTRL_TASK_PARAMETERS" ADD ("SYSTEM_NAME" VARCHAR2(128));
ALTER TABLE "SESS_QUEUE" ADD ("SYSTEM_NAME" VARCHAR2(128));
ALTER TABLE "SESS_STATUS" ADD ("SYSTEM_NAME" VARCHAR2(128));
ALTER TABLE "STAT_STATUS" ADD ("SYSTEM_NAME" VARCHAR2(128));
ALTER TABLE "TEMP_ENG_JOB_RUNNING" ADD ("SYSTEM_NAME" VARCHAR2(128));




--MUJ PRIDAVEK
ALTER TABLE "SESS_JOB" ADD ("SYSTEM_NAME" VARCHAR2(128));
ALTER TABLE "SESS_JOB_BCKP" ADD ("SYSTEM_NAME" VARCHAR2(128));

ALTER TABLE "STAT_LOG_MESSAGE_HIST" ADD ("SYSTEM_NAME" VARCHAR2(128));
ALTER TABLE "STAT_LOG_EVENT_HIST" ADD ("SYSTEM_NAME" VARCHAR2(128));



