ALTER TABLE SESS_QUEUE ADD (system_name VARCHAR2(128));
COMMENT ON COLUMN "SESS_QUEUE"."SYSTEM_NAME" IS 'Name of the system / ETL server on which is job running';

ALTER TABLE CTRL_TASK_PARAMETERS RENAME TO CTRL_TASK_PARAMETERS_BCKP;

  CREATE TABLE "CTRL_TASK_PARAMETERS" 
   (	"PARAM_NAME" VARCHAR2(128 BYTE), 
	"PARAM_TYPE" VARCHAR2(128 BYTE), 
	"PARAM_VAL_INT_CURR" NUMBER(38,0), 
	"PARAM_VAL_INT_MAX" NUMBER(38,0), 
	"PARAM_VAL_INT_DEFAULT" NUMBER(38,0) NOT NULL ENABLE, 
	"PARAM_DIMENSION" VARCHAR2(128 BYTE), 
	"TASK_SUBTYPE" VARCHAR2(128 BYTE), 
	"TASK_TYPE" VARCHAR2(128 BYTE), 
	"VALID_FROM" NUMBER(38,0) NOT NULL ENABLE, 
	"VALID_TO" NUMBER(38,0) NOT NULL ENABLE, 
	"ENGINE_ID" NUMBER(38,0) NOT NULL ENABLE,
	"SYSTEM_NAME" VARCHAR2(128) NULL,
	"DESCRIPTION" VARCHAR2(1024 BYTE)
   );

   COMMENT ON COLUMN "CTRL_TASK_PARAMETERS"."PARAM_NAME" IS 'Parameter name';
   COMMENT ON COLUMN "CTRL_TASK_PARAMETERS"."PARAM_TYPE" IS 'Parameter type';
   COMMENT ON COLUMN "CTRL_TASK_PARAMETERS"."PARAM_VAL_INT_CURR" IS 'Current value of number of job running in';
   COMMENT ON COLUMN "CTRL_TASK_PARAMETERS"."PARAM_VAL_INT_MAX" IS 'Maximal number which can be reach for category or subcategory';
   COMMENT ON COLUMN "CTRL_TASK_PARAMETERS"."PARAM_VAL_INT_DEFAULT" IS 'Default maximal number set for category or subcategory';
   COMMENT ON COLUMN "CTRL_TASK_PARAMETERS"."TASK_SUBTYPE" IS 'Job category or subcategory for parallelism control ';
   COMMENT ON COLUMN "CTRL_TASK_PARAMETERS"."TASK_TYPE" IS 'Job category for parallelism control ';
   COMMENT ON COLUMN "CTRL_TASK_PARAMETERS"."VALID_FROM" IS 'From which hour is values valid';
   COMMENT ON COLUMN "CTRL_TASK_PARAMETERS"."VALID_TO" IS 'To which hour is values valid';
   COMMENT ON COLUMN "CTRL_TASK_PARAMETERS"."ENGINE_ID" IS 'Engine identification';
   COMMENT ON COLUMN "CTRL_TASK_PARAMETERS"."SYSTEM_NAME" IS 'Name of the system / ETL server for which the parameter is valid';
   COMMENT ON COLUMN "CTRL_TASK_PARAMETERS"."DESCRIPTION" IS 'Description of parameter';
   COMMENT ON TABLE "CTRL_TASK_PARAMETERS"  IS 'Job category setting table for parallelism control ';
   
INSERT INTO CTRL_TASK_PARAMETERS
SELECT 	param_name, param_type, param_val_int_curr, param_val_int_max, param_val_int_default, param_dimension, task_subtype, task_type, valid_from, valid_to, engine_id, NULL, description
FROM CTRL_TASK_PARAMETERS_BCKP
WHERE param_type = 'TOUGH_CATEGORY_CONTROL';

INSERT INTO CTRL_TASK_PARAMETERS
SELECT 	param_name, param_type, param_val_int_curr, param_val_int_max, param_val_int_default, param_dimension, task_subtype, task_type, valid_from, valid_to, engine_id, 'SYSTEM_A', description
FROM CTRL_TASK_PARAMETERS_BCKP
WHERE param_type <> 'TOUGH_CATEGORY_CONTROL';

INSERT INTO CTRL_TASK_PARAMETERS
SELECT 	param_name, param_type, param_val_int_curr, param_val_int_max, param_val_int_default, param_dimension, task_subtype, task_type, valid_from, valid_to, engine_id, 'SYSTEM_B', description
FROM CTRL_TASK_PARAMETERS_BCKP
WHERE param_type <> 'TOUGH_CATEGORY_CONTROL';

COMMIT;

ALTER TABLE STAT_STATUS RENAME TO STAT_STATUS_BCKP;

  CREATE TABLE "STAT_STATUS" 
   (	"JOB_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"JOB_NAME" VARCHAR2(128 BYTE) NOT NULL ENABLE, 
	"STREAM_NAME" VARCHAR2(128 BYTE) NOT NULL ENABLE, 
	"STATUS_TS" TIMESTAMP (6) NOT NULL ENABLE, 
	"LOAD_DATE" DATE NOT NULL ENABLE, 
	"STATUS" NUMBER(38,0), 
	"N_RUN" NUMBER(38,0) NOT NULL ENABLE, 
	"SIGNAL" VARCHAR2(16 BYTE) NOT NULL ENABLE, 
	"APPLICATION_ID" NUMBER(38,0), 
	"ENGINE_ID" NUMBER(38,0) NOT NULL ENABLE,
	"SYSTEM_NAME" VARCHAR2(128),
	"DWH_DATE" DATE, 
	CHECK ("STATUS" IS NOT NULL) ENABLE
   ) ;

   COMMENT ON COLUMN "STAT_STATUS"."JOB_ID" IS 'Job identification';
   COMMENT ON COLUMN "STAT_STATUS"."JOB_NAME" IS 'Name of the job';
   COMMENT ON COLUMN "STAT_STATUS"."STREAM_NAME" IS 'Name of the stream';
   COMMENT ON COLUMN "STAT_STATUS"."STATUS_TS" IS 'Timestamp of status change';
   COMMENT ON COLUMN "STAT_STATUS"."LOAD_DATE" IS 'Load date';
   COMMENT ON COLUMN "STAT_STATUS"."STATUS" IS 'Job status';
   COMMENT ON COLUMN "STAT_STATUS"."N_RUN" IS 'Number of job launching';
   COMMENT ON COLUMN "STAT_STATUS"."SIGNAL" IS 'Signal which changed the status';
   COMMENT ON COLUMN "STAT_STATUS"."APPLICATION_ID" IS 'Application identification which drives the job';
   COMMENT ON COLUMN "STAT_STATUS"."ENGINE_ID" IS 'Engine ID';
   COMMENT ON COLUMN "STAT_STATUS"."SYSTEM_NAME" IS 'System name where status change was applied';
   COMMENT ON COLUMN "STAT_STATUS"."DWH_DATE" IS 'DWH date';
   COMMENT ON TABLE "STAT_STATUS"  IS 'History table for job status trace';

INSERT INTO "STAT_STATUS" 
SELECT job_id, job_name, stream_name, status_ts, load_date, status, n_run, signal, application_id, engine_id, NULL, dwh_date
FROM STAT_STATUS_BCKP
    ;

ALTER TABLE SESS_STATUS ADD (system_name VARCHAR2(128));
COMMENT ON COLUMN "SESS_STATUS"."SYSTEM_NAME" IS 'System name where status change was applied';

ALTER TABLE TEMP_ENG_JOB_RUNNING ADD (system_name VARCHAR2(128));

INSERT INTO CTRL_PARAMETERS (
	PARAM_NAME,
	PARAM_CD,
	PARAM_TYPE,
	PARAM_VAL_INT,
	PARAM_VAL_CHAR,
	PARAM_VAL_DATE,
	PARAM_VAL_TS,
	DESCRIPTION
) VALUES (
	'SYSTEM_OFF',
	NULL,
	'SCHEDULER',
	0,
	'SYSTEM_A',
	NULL,
	CURRENT_TIMESTAMP,
	'SYSTEM OFF, 0=system available, 1=system disabled'
);
INSERT INTO CTRL_PARAMETERS (
	PARAM_NAME,
	PARAM_CD,
	PARAM_TYPE,
	PARAM_VAL_INT,
	PARAM_VAL_CHAR,
	PARAM_VAL_DATE,
	PARAM_VAL_TS,
	DESCRIPTION
) VALUES (
	'SYSTEM_OFF',
	NULL,
	'SCHEDULER',
	0,
	'SYSTEM_B',
	NULL,
	CURRENT_TIMESTAMP,
	'SYSTEM OFF, 0=system available, 1=system disabled'
);
INSERT INTO CTRL_PARAMETERS (
	PARAM_NAME,
	PARAM_CD,
	PARAM_TYPE,
	PARAM_VAL_INT,
	PARAM_VAL_CHAR,
	PARAM_VAL_DATE,
	PARAM_VAL_TS,
	DESCRIPTION
) VALUES (
	'ENGINE_CONTROL',
	0,
	'SCHEDULER',
	0,
	'SYSTEM_B',
	NULL,
	CURRENT_TIMESTAMP,
	'Engine control 0=give control, 1=take control for system param_val_char'
);

DELETE FROM CTRL_PARAMETERS WHERE param_name = 'ENGINE_STATUS';

INSERT INTO CTRL_PARAMETERS (
	PARAM_NAME,
	PARAM_CD,
	PARAM_TYPE,
	PARAM_VAL_INT,
	PARAM_VAL_CHAR,
	PARAM_VAL_DATE,
	PARAM_VAL_TS,
	DESCRIPTION
) VALUES (
	'ENGINE_STATUS',
	0,
	'SCHEDULER',
	NULL,
	'SYSTEM_A',
	NULL,
	CURRENT_TIMESTAMP,
	'Engine last cycle timestamp on system'
);

INSERT INTO CTRL_PARAMETERS (
	PARAM_NAME,
	PARAM_CD,
	PARAM_TYPE,
	PARAM_VAL_INT,
	PARAM_VAL_CHAR,
	PARAM_VAL_DATE,
	PARAM_VAL_TS,
	DESCRIPTION
) VALUES (
	'ENGINE_STATUS',
	0,
	'SCHEDULER',
	NULL,
	'SYSTEM_B',
	NULL,
	CURRENT_TIMESTAMP,
	'Engine last cycle timestamp on system'
);


COMMIT;

INSERT INTO CTRL_TASK_PARAMETERS VALUES (NULL, 'PARALLELISM_CONTROL', 0, 150, 150, NULL, 'W', 'W_GROUP', 0, 99999999, 0, 'PDC', NULL);
INSERT INTO CTRL_TASK_PARAMETERS VALUES (NULL, 'TASK_MIN_CONTROL', 0, 6, 6, NULL, 'W', 'W_GROUP', 0, 99999999, 0, 'PDC', NULL);
INSERT INTO CTRL_TASK_PARAMETERS VALUES (NULL, 'PARALLELISM_CONTROL', 0, 150, 150, NULL, 'W_GROUP', 'W_GROUP', 0, 99999999, 0, 'PDC', NULL);
INSERT INTO CTRL_TASK_PARAMETERS VALUES (NULL, 'TASK_MIN_CONTROL', 0, 6, 6, NULL, 'W_GROUP', 'W_GROUP', 0, 99999999, 0, 'PDC', NULL);

INSERT INTO CTRL_TASK_PARAMETERS VALUES (NULL, 'PARALLELISM_CONTROL', 0, 150, 150, NULL, 'W', 'W_GROUP', 0, 99999999, 0, 'SYSTEM_B', NULL);
INSERT INTO CTRL_TASK_PARAMETERS VALUES (NULL, 'TASK_MIN_CONTROL', 0, 6, 6, NULL, 'W', 'W_GROUP', 0, 99999999, 0, 'SYSTEM_B', NULL);
INSERT INTO CTRL_TASK_PARAMETERS VALUES (NULL, 'PARALLELISM_CONTROL', 0, 150, 150, NULL, 'W_GROUP', 'W_GROUP', 0, 99999999, 0, 'SYSTEM_B', NULL);
INSERT INTO CTRL_TASK_PARAMETERS VALUES (NULL, 'TASK_MIN_CONTROL', 0, 6, 6, NULL, 'W_GROUP', 'W_GROUP', 0, 99999999, 0, 'SYSTEM_B', NULL);

INSERT INTO CTRL_TASK_PARAMETERS VALUES (NULL, 'PARALLELISM_CONTROL', 0, 150, 150, NULL, 'D', 'D_GROUP', 0, 99999999, 0, 'PDC', NULL);
INSERT INTO CTRL_TASK_PARAMETERS VALUES (NULL, 'TASK_MIN_CONTROL', 0, 6, 6, NULL, 'D', 'D_GROUP', 0, 99999999, 0, 'PDC', NULL);
INSERT INTO CTRL_TASK_PARAMETERS VALUES (NULL, 'PARALLELISM_CONTROL', 0, 150, 150, NULL, 'D_GROUP', 'D_GROUP', 0, 99999999, 0, 'PDC', NULL);
INSERT INTO CTRL_TASK_PARAMETERS VALUES (NULL, 'TASK_MIN_CONTROL', 0, 6, 6, NULL, 'D_GROUP', 'D_GROUP', 0, 99999999, 0, 'PDC', NULL);

INSERT INTO CTRL_TASK_PARAMETERS VALUES (NULL, 'PARALLELISM_CONTROL', 0, 150, 150, NULL, 'D', 'D_GROUP', 0, 99999999, 0, 'SYSTEM_B', NULL);
INSERT INTO CTRL_TASK_PARAMETERS VALUES (NULL, 'TASK_MIN_CONTROL', 0, 6, 6, NULL, 'D', 'D_GROUP', 0, 99999999, 0, 'SYSTEM_B', NULL);
INSERT INTO CTRL_TASK_PARAMETERS VALUES (NULL, 'PARALLELISM_CONTROL', 0, 150, 150, NULL, 'D_GROUP', 'D_GROUP', 0, 99999999, 0, 'SYSTEM_B', NULL);
INSERT INTO CTRL_TASK_PARAMETERS VALUES (NULL, 'TASK_MIN_CONTROL', 0, 6, 6, NULL, 'D_GROUP', 'D_GROUP', 0, 99999999, 0, 'SYSTEM_B', NULL);

INSERT INTO CTRL_TASK_PARAMETERS VALUES (NULL, 'PARALLELISM_CONTROL', 0, 150, 150, NULL, 'C', 'C_GROUP', 0, 99999999, 0, 'PDC', NULL);
INSERT INTO CTRL_TASK_PARAMETERS VALUES (NULL, 'TASK_MIN_CONTROL', 0, 6, 6, NULL, 'C', 'C_GROUP', 0, 99999999, 0, 'PDC', NULL);
INSERT INTO CTRL_TASK_PARAMETERS VALUES (NULL, 'PARALLELISM_CONTROL', 0, 150, 150, NULL, 'C_GROUP', 'C_GROUP', 0, 99999999, 0, 'PDC', NULL);
INSERT INTO CTRL_TASK_PARAMETERS VALUES (NULL, 'TASK_MIN_CONTROL', 0, 6, 6, NULL, 'C_GROUP', 'C_GROUP', 0, 99999999, 0, 'PDC', NULL);

INSERT INTO CTRL_TASK_PARAMETERS VALUES (NULL, 'PARALLELISM_CONTROL', 0, 150, 150, NULL, 'C', 'C_GROUP', 0, 99999999, 0, 'SYSTEM_B', NULL);
INSERT INTO CTRL_TASK_PARAMETERS VALUES (NULL, 'TASK_MIN_CONTROL', 0, 6, 6, NULL, 'C', 'C_GROUP', 0, 99999999, 0, 'SYSTEM_B', NULL);
INSERT INTO CTRL_TASK_PARAMETERS VALUES (NULL, 'PARALLELISM_CONTROL', 0, 150, 150, NULL, 'C_GROUP', 'C_GROUP', 0, 99999999, 0, 'SYSTEM_B', NULL);
INSERT INTO CTRL_TASK_PARAMETERS VALUES (NULL, 'TASK_MIN_CONTROL', 0, 6, 6, NULL, 'C_GROUP', 'C_GROUP', 0, 99999999, 0, 'SYSTEM_B', NULL);

INSERT INTO CTRL_TASK_PARAMETERS VALUES (NULL, 'PARALLELISM_CONTROL', 0, 150, 150, NULL, 'R', 'R_GROUP', 0, 99999999, 0, 'PDC', NULL);
INSERT INTO CTRL_TASK_PARAMETERS VALUES (NULL, 'TASK_MIN_CONTROL', 0, 6, 6, NULL, 'R', 'R_GROUP', 0, 99999999, 0, 'PDC', NULL);
INSERT INTO CTRL_TASK_PARAMETERS VALUES (NULL, 'PARALLELISM_CONTROL', 0, 150, 150, NULL, 'R_GROUP', 'R_GROUP', 0, 99999999, 0, 'PDC', NULL);
INSERT INTO CTRL_TASK_PARAMETERS VALUES (NULL, 'TASK_MIN_CONTROL', 0, 6, 6, NULL, 'R_GROUP', 'R_GROUP', 0, 99999999, 0, 'PDC', NULL);

INSERT INTO CTRL_TASK_PARAMETERS VALUES (NULL, 'PARALLELISM_CONTROL', 0, 150, 150, NULL, 'R', 'R_GROUP', 0, 99999999, 0, 'SYSTEM_B', NULL);
INSERT INTO CTRL_TASK_PARAMETERS VALUES (NULL, 'TASK_MIN_CONTROL', 0, 6, 6, NULL, 'R', 'R_GROUP', 0, 99999999, 0, 'SYSTEM_B', NULL);
INSERT INTO CTRL_TASK_PARAMETERS VALUES (NULL, 'PARALLELISM_CONTROL', 0, 150, 150, NULL, 'R_GROUP', 'R_GROUP', 0, 99999999, 0, 'SYSTEM_B', NULL);
INSERT INTO CTRL_TASK_PARAMETERS VALUES (NULL, 'TASK_MIN_CONTROL', 0, 6, 6, NULL, 'R_GROUP', 'R_GROUP', 0, 99999999, 0, 'SYSTEM_B', NULL);

INSERT INTO CTRL_TASK_PARAMETERS VALUES (NULL, 'PARALLELISM_CONTROL', 0, 150, 150, NULL, 'INFORMATICA', 'INFORMATICA_GROUP', 0, 99999999, 0, 'PDC', NULL);
INSERT INTO CTRL_TASK_PARAMETERS VALUES (NULL, 'TASK_MIN_CONTROL', 0, 6, 6, NULL, 'INFORMATICA', 'INFORMATICA_GROUP', 0, 99999999, 0, 'PDC', NULL);
INSERT INTO CTRL_TASK_PARAMETERS VALUES (NULL, 'PARALLELISM_CONTROL', 0, 150, 150, NULL, 'INFORMATICA_GROUP', 'INFORMATICA_GROUP', 0, 99999999, 0, 'PDC', NULL);
INSERT INTO CTRL_TASK_PARAMETERS VALUES (NULL, 'TASK_MIN_CONTROL', 0, 6, 6, NULL, 'INFORMATICA_GROUP', 'INFORMATICA_GROUP', 0, 99999999, 0, 'PDC', NULL);

INSERT INTO CTRL_TASK_PARAMETERS VALUES (NULL, 'PARALLELISM_CONTROL', 0, 150, 150, NULL, 'INFORMATICA', 'INFORMATICA_GROUP', 0, 99999999, 0, 'SYSTEM_B', NULL);
INSERT INTO CTRL_TASK_PARAMETERS VALUES (NULL, 'TASK_MIN_CONTROL', 0, 6, 6, NULL, 'INFORMATICA', 'INFORMATICA_GROUP', 0, 99999999, 0, 'SYSTEM_B', NULL);
INSERT INTO CTRL_TASK_PARAMETERS VALUES (NULL, 'PARALLELISM_CONTROL', 0, 150, 150, NULL, 'INFORMATICA_GROUP', 'INFORMATICA_GROUP', 0, 99999999, 0, 'SYSTEM_B', NULL);
INSERT INTO CTRL_TASK_PARAMETERS VALUES (NULL, 'TASK_MIN_CONTROL', 0, 6, 6, NULL, 'INFORMATICA_GROUP', 'INFORMATICA_GROUP', 0, 99999999, 0, 'SYSTEM_B', NULL);
