ALTER TABLE SESS_QUEUE
ALTER COLUMN RUNNING_JOB_PID NUMBER;

COMMENT ON COLUMN SESS_QUEUE.QUEUE_NUMBER is 'PID of Run_job.pl';

Insert into CTRL_JOB_STATUS (STATUS,RUNABLE,DELAY_MINUTES,FINISHED,FINISHED_SUCCESSFULLY,EXECUTABLE,SORTING_ORDER,DESCRIPTION) 
values ('33','FAILED','0','0','0','1',(SELECT MAX(SORTING_ORDER)+1 FROM CTRL_JOB_STATUS),'Failed - Run_job.pl failure');

Insert into CTRL_JOB_STATUS (STATUS,RUNABLE,DELAY_MINUTES,FINISHED,FINISHED_SUCCESSFULLY,EXECUTABLE,SORTING_ORDER,DESCRIPTION) 
values ('1033','BLOCKED','0','0','0','0',(SELECT MAX(SORTING_ORDER)+1 FROM CTRL_JOB_STATUS),'Blocked - Run_job.pl failure');


Insert into CTRL_NEXT_STATUS (STATUS_IN,STATUS_OUT,SIGNAL,REQUEST,LAUNCH,CONT_ANYWAY) values ('33','1033','BLOCK','BLOCK','0','0');
Insert into CTRL_NEXT_STATUS (STATUS_IN,STATUS_OUT,SIGNAL,REQUEST,LAUNCH,CONT_ANYWAY) values ('1','33','RJ_FAILED','RJ_FAILED','0','0');
Insert into CTRL_NEXT_STATUS (STATUS_IN,STATUS_OUT,SIGNAL,REQUEST,LAUNCH,CONT_ANYWAY) values ('4','33','RJ_FAILED','RJ_FAILED','0','0');
Insert into CTRL_NEXT_STATUS (STATUS_IN,STATUS_OUT,SIGNAL,REQUEST,LAUNCH,CONT_ANYWAY) values ('33','8','MARK_FINISHED','MARK_FINISHED','0','0');
Insert into CTRL_NEXT_STATUS (STATUS_IN,STATUS_OUT,SIGNAL,REQUEST,LAUNCH,CONT_ANYWAY) values ('33','4','START','SUCCESS','1','0');
Insert into CTRL_NEXT_STATUS (STATUS_IN,STATUS_OUT,SIGNAL,REQUEST,LAUNCH,CONT_ANYWAY) values ('1033','33','UNBLOCK','BLOCK','0','0');
