ALTER TABLE CTRL_NOTIFICATION ADD (FINISHED_AFTER_INIT_TOLERANCE NUMBER(38,0));
comment on column CTRL_NOTIFICATION.FINISHED_AFTER_INIT_TOLERANCE is 'Number of minutes passed after init before event job not finish on time.';

INSERT INTO LKP_ERROR_CD (ERROR_CD, ERROR_CD_NAME, ERROR_CD_NAME_SHORT, ERROR_CD_DESC, ERROR_CD_RECOM) 
VALUES ('NO_FINISH_INIT', 'NOT_FINISHED_AFTER_INIT', 'NFINIT', 'Job not finished after init - time tolerance passed.', 'Reccommendation');

INSERT INTO "CTRL_NOTIFICATION_SEVERITY" (ERROR_CD, SEVERITY_LEVEL_CD) VALUES ('NO_FINISH_INIT', '2');
