<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="CTRL_JOB.aspx.cs" Inherits="PDC.CTRL_JOB" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
    <div class="PortletBoxInner">
        <p>
            <span class="ModuleHeader">CTRL_JOB</span>
            <br />
            Rowcount:&nbsp;<asp:Label ID="lDetailRowCount" runat="server" Text="-" EnableViewState="False"></asp:Label>
        </p>
        <div class="breaker_portlet">&nbsp;</div>
        <p>
                <span class="ModuleHeader">Current Label:</span>
                <asp:Label ID="lTChangeManagementLabel" runat="server" Text="N/A" EnableViewState="false"></asp:Label>
        </p>
        <p>
            <asp:Label ID="lNoLabelSelected" CssClass="infoLabel" runat="server" EnableViewState="False" Visible="True">Editable mode disabled. You have to set the label first.&nbsp;<a href="CtrlTables.aspx" class="infoLabel">Set Label</a></asp:Label>
        </p>
    </div>
    <!-- inner portlet 2 tab test  -->

    <asp:Panel ID="p_Detail_lvl1" runat="server" EnableViewState="False" CssClass="PortletBoxInner">
    
    
        <p class="PDCPagingInfo"><asp:Label ID="PagingInformation" runat="server" Text=""></asp:Label>
        &nbsp;
        Number of rows per page:
        &nbsp;
        <asp:DropDownList 
                ID="PagerCountperPage" runat="server" AutoPostBack="True" 
                onselectedindexchanged="PagerCountperPage_SelectedIndexChanged">
            <asp:ListItem>10</asp:ListItem>
            <asp:ListItem>20</asp:ListItem>
            <asp:ListItem>50</asp:ListItem>
            <asp:ListItem>100</asp:ListItem><asp:ListItem>200</asp:ListItem>
            <asp:ListItem>500</asp:ListItem>
            
            </asp:DropDownList>
        </p>
        <div class="scrollable"><asp:GridView ID="gv_list" runat="server" DataSourceID="SqlDataSource1" AllowPaging="True"
            PageSize="<%$ AppSettings:DefaultPageItemCount %>" AllowSorting="True" AutoGenerateColumns="False"
            CellPadding="2" CellSpacing="1" GridLines="None" CssClass="PDCTbl" EmptyDataText="No rows"
             EnableViewState="False" DataKeyNames="JOB_NAME"
            PagerSettings-Mode="NumericFirstLast" PagerSettings-Position="TopAndBottom" 
            ondatabound="GridView2_DataBound" AutoGenerateEditButton="True" AutoGenerateDeleteButton="True"
            OnRowUpdating="GridView2_RowUpdating"
            EditRowStyle-Width="100">

<PagerSettings Mode="NumericFirstLast" Position="TopAndBottom"></PagerSettings>

            <RowStyle CssClass="PDCTblRow" Wrap="False" />
            <SelectedRowStyle CssClass="PDCTblSelRow" />
            <SortedAscendingHeaderStyle CssClass="sort_asc" />
            <SortedDescendingHeaderStyle CssClass="sort_desc" />
            <AlternatingRowStyle CssClass="PDCTblEvenRow" />
            <HeaderStyle CssClass="PDCTblHeader" />
            <Columns>
                <asp:BoundField DataField="JOB_NAME" HeaderText="JOB_NAME" />
                <asp:TemplateField SortExpression="STREAM_NAME" HeaderText="STREAM_NAME" >
                    <EditItemTemplate>
                        <asp:DropDownList DataSourceID="SqlDataSource_CTRL_STREAM" DataTextField="LKP_VAL_DESC" DataValueField="LKP_VAL_DESC" ID="DDListSTREAM" Runat="server" SelectedValue='<%# Bind("STREAM_NAME") %>' >
                    </asp:DropDownList>
                    </EditItemTemplate>
                    <ItemTemplate >
                        <asp:Label Runat="server" Text='<%# Bind("STREAM_NAME") %>' ID="Label1STREAM_NAME"></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>

                <asp:BoundField DataField="PRIORITY" HeaderText="PRIORITY" />
                <asp:BoundField DataField="CMD_LINE" HeaderText="CMD_LINE" />
                <asp:BoundField DataField="SRC_SYS_ID" HeaderText="SRC_SYS_ID" />

                <asp:TemplateField SortExpression="PHASE" HeaderText="PHASE" >
                    <EditItemTemplate>
                        <asp:DropDownList DataSourceID="SqlDataSource_LKP_PHASE" DataTextField="LKP_VAL_DESC" DataValueField="LKP_VAL_DESC" ID="DDListPHASE" Runat="server" SelectedValue='<%# Bind("PHASE") %>' >
                    </asp:DropDownList>
                    </EditItemTemplate>
                    <ItemTemplate >
                        <asp:Label Runat="server" Text='<%# Bind("PHASE") %>' ID="Label1PHASE"></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>

                <asp:BoundField DataField="TABLE_NAME" HeaderText="TABLE_NAME" />

                <asp:TemplateField SortExpression="JOB_CATEGORY" HeaderText="JOB_CATEGORY" >
                    <EditItemTemplate>
                        <asp:DropDownList DataSourceID="SqlDataSource_LKP_JOB_CATEGORY" DataTextField="LKP_VAL_DESC" DataValueField="LKP_VAL_DESC" ID="DDListJOB_CATEGORY" Runat="server" SelectedValue='<%# Bind("JOB_CATEGORY") %>' >
                    </asp:DropDownList>
                    </EditItemTemplate>
                    <ItemTemplate >
                        <asp:Label Runat="server" Text='<%# Bind("JOB_CATEGORY") %>' ID="Label1JOB_CATEGORY"></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField SortExpression="JOB_TYPE" HeaderText="JOB_TYPE" >
                    <EditItemTemplate>
                        <asp:DropDownList DataSourceID="SqlDataSource_LKP_JOB_TYPE" DataTextField="LKP_VAL_DESC" DataValueField="LKP_VAL_DESC" ID="DDListJOB_TYPE" Runat="server" SelectedValue='<%# Bind("JOB_TYPE") %>' >
                    </asp:DropDownList>
                    </EditItemTemplate>
                    <ItemTemplate >
                        <asp:Label Runat="server" Text='<%# Bind("JOB_TYPE") %>' ID="Label1JOB_TYPE"></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField SortExpression="TOUGHNESS" HeaderText="TOUGHNESS" >
                    <EditItemTemplate>
                        <asp:DropDownList DataSourceID="SqlDataSource_LKP_TOUGHNESS" DataTextField="LKP_VAL_DESC" DataValueField="LKP_VAL_DESC" ID="DDListTOUGHNESS" Runat="server" SelectedValue='<%# Bind("TOUGHNESS") %>' >
                    </asp:DropDownList>
                    </EditItemTemplate>
                    <ItemTemplate >
                        <asp:Label Runat="server" Text='<%# Bind("TOUGHNESS") %>' ID="Label1JOB_TYPE"></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:BoundField DataField="CONT_ANYWAY" HeaderText="CONT_ANYWAY" />
                <asp:BoundField DataField="MAX_RUNS" HeaderText="MAX_RUNS" />
                <asp:BoundField DataField="ALWAYS_RESTART" HeaderText="ALWAYS_RESTART" />
                <asp:BoundField DataField="STATUS_BEGIN" HeaderText="STATUS_BEGIN" />
                <asp:BoundField DataField="WAITING_HR" HeaderText="WAITING_HR" />
                <asp:BoundField DataField="DEADLINE_HR" HeaderText="DEADLINE_HR" />

                <asp:TemplateField SortExpression="ENGINE_ID" HeaderText="ENGINE_ID" >
                    <EditItemTemplate>
                        <asp:DropDownList DataSourceID="SqlDataSource_SESS_QUEUE" DataTextField="LKP_VAL_DESC" DataValueField="LKP_VAL_DESC" ID="DDListENGINE_ID" Runat="server" SelectedValue='<%# Bind("ENGINE_ID") %>' >
                    </asp:DropDownList>
                    </EditItemTemplate>
                    <ItemTemplate >
                        <asp:Label Runat="server" Text='<%# Bind("ENGINE_ID") %>' ID="Label1ENGINE_ID"></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>

                <asp:BoundField DataField="JOB_DESC" HeaderText="JOB_DESC" />
                <asp:BoundField DataField="AUTHOR" HeaderText="AUTHOR" />
                <asp:BoundField DataField="NOTE" HeaderText="NOTE" />
            </Columns>

            <EditRowStyle Width="100px"></EditRowStyle>
            <PagerStyle CssClass="PDCTblPaging" />

            <FooterStyle CssClass="PDCTblFooter" />
        </asp:GridView></div>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
            onselected="SqlDataSource_Selected" 
            onselecting="SqlDataSource_Selecting"
            ConnectionString="<%$ ConnectionStrings:PDCOracleConnection.connectionString %>"
            ProviderName="<%$ ConnectionStrings:PDCOracleConnection.ProviderName %>" EnableViewState="False" 
            SelectCommand="PCKG_GUI.SP_GUI_VIEW_CTRL_JOB" 
            SelectCommandType="StoredProcedure"

            UpdateCommandType="StoredProcedure" 
            UpdateCommand="PCKG_GUI.SP_GUI_UPDT_CTRL_JOB" 
            onupdating="SqlDataSource_Updating"
            OnUpdated="SqlDataSource_Updated"
            
             DeleteCommand="PCKG_GUI.SP_GUI_UPDT_CTRL_JOB_DEL"
            DeleteCommandType="StoredProcedure"
            OnDeleting="SqlDataSource_Deleting" OnDeleted="SqlDataSource_Deleted"

            >
             <SelectParameters>
                     
            <asp:ControlParameter Name="ENG_ID_IN" Direction="Input" DefaultValue="0" DbType="String" Size="255" ControlID="dropdown_PDCEngine" PropertyName="SelectedValue" />
            <asp:Parameter Name="USER_IN" Direction="Input" DefaultValue="DBG_USER" DbType="String" Size="255"/>
            <asp:Parameter Name="DEBUG_IN" Direction="Input" DefaultValue="0" DbType="String" Size="255"/>
            <asp:SessionParameter Name="FLT_STREAM_NAME_IN" Direction="Input" DefaultValue=" " DbType="String" Size="255"/>
            <asp:SessionParameter Name="FLT_JOB_NAME_IN" Direction="Input" DefaultValue=" " DbType="String" Size="255"/>
            <asp:SessionParameter Name="FLT_JOB_TYPE_IN" Direction="Input" DefaultValue=" " DbType="String" Size="255"/>
            <asp:SessionParameter Name="FLT_TABLE_NAME_IN" Direction="Input" DefaultValue=" " DbType="String" Size="255"/>
            <asp:SessionParameter Name="FLT_PHASE_IN" Direction="Input" DefaultValue=" " DbType="String" Size="255"/>
            <asp:SessionParameter Name="FLT_JOB_CATEGORY_IN" Direction="Input" DefaultValue=" " DbType="String" Size="255"/>
            <asp:Parameter Name="EXIT_CD_OUT" Direction="Output" DefaultValue="" DbType="String" Size="255"/>
            <asp:Parameter Name="ERRMSG_OUT" Direction="Output" DefaultValue="" DbType="String" Size="255"/>
            <asp:Parameter Name="ERRCODE_OUT" Direction="Output" DefaultValue="" DbType="String" Size="255"/>
            <asp:Parameter Name="ERRLINE_OUT" Direction="Output" DefaultValue="" DbType="String" Size="255"/>

             <asp:SessionParameter Name="VALUES_OUT" Direction="Output" DefaultValue="" DbType="String" Size="255"/>

        </SelectParameters>
            <UpdateParameters>
    
              <asp:ControlParameter Name="ENG_ID_IN" Direction="Input" DefaultValue="0" DbType="String" Size="255" ControlID="dropdown_PDCEngine" PropertyName="SelectedValue" />
            <asp:Parameter Name="USER_IN" Direction="Input" DefaultValue="DBG_USER" DbType="String" Size="255"/>
             
                <asp:Parameter Name="DEBUG_IN" Direction="Input" DefaultValue="0" DbType="String" />
                <asp:Parameter Name="EXIT_CD_OUT" Direction="Output" DbType="String" Size="255" />
                <asp:Parameter Name="ERRMSG_OUT" Direction="Output" DbType="String" Size="255" />
                <asp:Parameter Name="ERRCODE_OUT" Direction="Output" DbType="String" Size="255" />
                <asp:Parameter Name="ERRLINE_OUT" Direction="Output" DbType="String" Size="255" />

                <asp:Parameter Name="JOB_NAME" DefaultValue="" Direction="Input" Type="String"  Size="255" />
                <asp:Parameter Name="STREAM_NAME" DefaultValue="" Direction="Input" Type="String"  Size="255" />
                <asp:Parameter Name="PRIORITY" DefaultValue="" Direction="Input" Type="Int32"  />
                <asp:Parameter Name="CMD_LINE" DefaultValue="" Direction="Input" Type="String"  Size="1000" />
                <asp:Parameter Name="SRC_SYS_ID" DefaultValue="" Direction="Input" Type="Int32"  />
                <asp:Parameter Name="PHASE" DefaultValue="" Direction="Input" Type="String"  Size="255" />
                <asp:Parameter Name="TABLE_NAME" DefaultValue="" Direction="Input" Type="String"  Size="255" />
                <asp:Parameter Name="JOB_CATEGORY" DefaultValue="" Direction="Input" Type="String"  Size="255" />
                <asp:Parameter Name="JOB_TYPE" DefaultValue="" Direction="Input" Type="String"  Size="255" />
                <asp:Parameter Name="TOUGHNESS" DefaultValue="" Direction="Input" Type="String"  Size="255" />
                <asp:Parameter Name="CONT_ANYWAY" DefaultValue="" Direction="Input" Type="Int32"  />
                <asp:Parameter Name="MAX_RUNS" DefaultValue="" Direction="Input" Type="Int32"   />
                <asp:Parameter Name="ALWAYS_RESTART" DefaultValue="" Direction="Input" Type="Int32"   />
                <asp:Parameter Name="STATUS_BEGIN" DefaultValue="" Direction="Input" Type="Int32"   />
                <asp:Parameter Name="WAITING_HR" DefaultValue="" Direction="Input" Type="Int32"   />
                <asp:Parameter Name="DEADLINE_HR" DefaultValue="" Direction="Input" Type="Int32"   />
                <asp:Parameter Name="ENGINE_ID" DefaultValue="" Direction="Input" Type="Int32"   />
                <asp:Parameter Name="JOB_DESC" DefaultValue="" Direction="Input" Type="String"  Size="255" />
                <asp:Parameter Name="AUTHOR" DefaultValue="" Direction="Input" Type="String"  Size="255" />
                <asp:Parameter Name="NOTE" DefaultValue="" Direction="Input" Type="String"  Size="255" />
                <asp:SessionParameter Name="LABEL_NAME_IN" Direction="Input" SessionField="TChangeManagementLabel" DbType="String" Size="255"/>

            </UpdateParameters>

        </asp:SqlDataSource>



        <asp:SqlDataSource ID="SqlDataSource_LKP_PHASE" runat="server" 
            ConnectionString="<%$ ConnectionStrings:PDCOracleConnection.connectionString %>"
            ProviderName="<%$ ConnectionStrings:PDCOracleConnection.ProviderName %>" 
            EnableViewState="False"
            SelectCommand="PCKG_GUI.SP_GUI_VIEW_LKP_PHASE"
                                    SelectCommandType="StoredProcedure"
                                    OnSelecting="SqlDataSource_Lookup_Selecting">
                                    <SelectParameters>
                                    <asp:ControlParameter Name="ENG_ID_IN" Direction="Input" DefaultValue="0" DbType="Int32" ControlID="dropdown_PDCEngine" PropertyName="SelectedValue" />
                                    <asp:Parameter Name="USER_IN" Direction="Input" DefaultValue="DBG_USER" DbType="String" Size="255"/>
                                    <asp:Parameter Name="DEBUG_IN" Direction="Input" DefaultValue="0" DbType="Int32"/>
                                    <asp:Parameter Name="EXIT_CD_OUT" Direction="Output" DefaultValue="" DbType="Int32"/>
                                    <asp:Parameter Name="ERRMSG_OUT" Direction="Output" DefaultValue="" DbType="String" Size="255"/>
                                    <asp:Parameter Name="ERRCODE_OUT" Direction="Output" DefaultValue="" DbType="Int32"/>
                                    <asp:Parameter Name="ERRLINE_OUT" Direction="Output" DefaultValue="" DbType="String" Size="255"/>           
                                    <asp:SessionParameter Name="VALUES_OUT" Direction="Output" DefaultValue="" DbType="String" Size="255"/>
                                    </SelectParameters>
        </asp:SqlDataSource>
        <asp:SqlDataSource ID="SqlDataSource_LKP_JOB_TYPE" runat="server" 
            ConnectionString="<%$ ConnectionStrings:PDCOracleConnection.connectionString %>"
            ProviderName="<%$ ConnectionStrings:PDCOracleConnection.ProviderName %>"
            EnableViewState="False"
            SelectCommand="PCKG_GUI.SP_GUI_VIEW_LKP_JOB_TYPE"
                                    SelectCommandType="StoredProcedure"
                                    OnSelecting="SqlDataSource_Lookup_Selecting">
                                    <SelectParameters>
                                    <asp:ControlParameter Name="ENG_ID_IN" Direction="Input" DefaultValue="0" DbType="Int32" ControlID="dropdown_PDCEngine" PropertyName="SelectedValue" />
                                    <asp:Parameter Name="USER_IN" Direction="Input" DefaultValue="DBG_USER" DbType="String" Size="255"/>
                                    <asp:Parameter Name="DEBUG_IN" Direction="Input" DefaultValue="0" DbType="Int32"/>
                                    <asp:Parameter Name="EXIT_CD_OUT" Direction="Output" DefaultValue="" DbType="Int32"/>
                                    <asp:Parameter Name="ERRMSG_OUT" Direction="Output" DefaultValue="" DbType="String" Size="255"/>
                                    <asp:Parameter Name="ERRCODE_OUT" Direction="Output" DefaultValue="" DbType="Int32"/>
                                    <asp:Parameter Name="ERRLINE_OUT" Direction="Output" DefaultValue="" DbType="String" Size="255"/>           
                                    <asp:SessionParameter Name="VALUES_OUT" Direction="Output" DefaultValue="" DbType="String" Size="255"/>
                                    </SelectParameters>
        </asp:SqlDataSource>
        <asp:SqlDataSource ID="SqlDataSource_LKP_JOB_CATEGORY" runat="server" 
            ConnectionString="<%$ ConnectionStrings:PDCOracleConnection.connectionString %>"
            ProviderName="<%$ ConnectionStrings:PDCOracleConnection.ProviderName %>" 
            EnableViewState="False"
            SelectCommand="PCKG_GUI.SP_GUI_VIEW_LKP_JOB_CATEGORY"
                                    SelectCommandType="StoredProcedure"
                                    OnSelecting="SqlDataSource_Lookup_Selecting">
                                    <SelectParameters>
                                    <asp:ControlParameter Name="ENG_ID_IN" Direction="Input" DefaultValue="0" DbType="Int32" ControlID="dropdown_PDCEngine" PropertyName="SelectedValue" />
                                    <asp:Parameter Name="USER_IN" Direction="Input" DefaultValue="DBG_USER" DbType="String" Size="255"/>
                                    <asp:Parameter Name="DEBUG_IN" Direction="Input" DefaultValue="0" DbType="Int32"/>
                                    <asp:Parameter Name="EXIT_CD_OUT" Direction="Output" DefaultValue="" DbType="Int32"/>
                                    <asp:Parameter Name="ERRMSG_OUT" Direction="Output" DefaultValue="" DbType="String" Size="255"/>
                                    <asp:Parameter Name="ERRCODE_OUT" Direction="Output" DefaultValue="" DbType="Int32"/>
                                    <asp:Parameter Name="ERRLINE_OUT" Direction="Output" DefaultValue="" DbType="String" Size="255"/>           
                                    <asp:SessionParameter Name="VALUES_OUT" Direction="Output" DefaultValue="" DbType="String" Size="255"/>
                                    </SelectParameters>
        </asp:SqlDataSource>
        <asp:SqlDataSource ID="SqlDataSource_SESS_QUEUE" runat="server" 
            ConnectionString="<%$ ConnectionStrings:PDCOracleConnection.connectionString %>"
            ProviderName="<%$ ConnectionStrings:PDCOracleConnection.ProviderName %>" 
            EnableViewState="False"
            SelectCommand="PCKG_GUI.SP_GUI_VIEW_SESS_QUEUE"
                                    SelectCommandType="StoredProcedure"
                                    OnSelecting="SqlDataSource_Lookup_Selecting">
                                    <SelectParameters>
                                    <asp:ControlParameter Name="ENG_ID_IN" Direction="Input" DefaultValue="0" DbType="Int32" ControlID="dropdown_PDCEngine" PropertyName="SelectedValue" />
                                    <asp:Parameter Name="USER_IN" Direction="Input" DefaultValue="DBG_USER" DbType="String" Size="255"/>
                                    <asp:Parameter Name="DEBUG_IN" Direction="Input" DefaultValue="0" DbType="Int32"/>
                                    <asp:Parameter Name="EXIT_CD_OUT" Direction="Output" DefaultValue="" DbType="Int32"/>
                                    <asp:Parameter Name="ERRMSG_OUT" Direction="Output" DefaultValue="" DbType="String" Size="255"/>
                                    <asp:Parameter Name="ERRCODE_OUT" Direction="Output" DefaultValue="" DbType="Int32"/>
                                    <asp:Parameter Name="ERRLINE_OUT" Direction="Output" DefaultValue="" DbType="String" Size="255"/>           
                                    <asp:SessionParameter Name="VALUES_OUT" Direction="Output" DefaultValue="" DbType="String" Size="255"/>
                                    </SelectParameters>
        </asp:SqlDataSource>
        <asp:SqlDataSource ID="SqlDataSource_LKP_TOUGHNESS" runat="server" 
            ConnectionString="<%$ ConnectionStrings:PDCOracleConnection.connectionString %>"
            ProviderName="<%$ ConnectionStrings:PDCOracleConnection.ProviderName %>" 
            EnableViewState="False"
            SelectCommand="PCKG_GUI.SP_GUI_VIEW_LKP_TOUGHNESS"
                                    SelectCommandType="StoredProcedure"
                                    OnSelecting="SqlDataSource_Lookup_Selecting">
                                    <SelectParameters>
                                    <asp:ControlParameter Name="ENG_ID_IN" Direction="Input" DefaultValue="0" DbType="Int32" ControlID="dropdown_PDCEngine" PropertyName="SelectedValue" />
                                    <asp:Parameter Name="USER_IN" Direction="Input" DefaultValue="DBG_USER" DbType="String" Size="255"/>
                                    <asp:Parameter Name="DEBUG_IN" Direction="Input" DefaultValue="0" DbType="Int32"/>
                                    <asp:Parameter Name="EXIT_CD_OUT" Direction="Output" DefaultValue="" DbType="Int32"/>
                                    <asp:Parameter Name="ERRMSG_OUT" Direction="Output" DefaultValue="" DbType="String" Size="255"/>
                                    <asp:Parameter Name="ERRCODE_OUT" Direction="Output" DefaultValue="" DbType="Int32"/>
                                    <asp:Parameter Name="ERRLINE_OUT" Direction="Output" DefaultValue="" DbType="String" Size="255"/>           
                                    <asp:SessionParameter Name="VALUES_OUT" Direction="Output" DefaultValue="" DbType="String" Size="255"/>
                                    </SelectParameters>
        </asp:SqlDataSource>
        <asp:SqlDataSource ID="SqlDataSource_CTRL_STREAM" runat="server" 
            ConnectionString="<%$ ConnectionStrings:PDCOracleConnection.connectionString %>"
            ProviderName="<%$ ConnectionStrings:PDCOracleConnection.ProviderName %>" 
            EnableViewState="False"
            SelectCommand="PCKG_GUI.SP_GUI_VIEW_CTRL_STREAM_NAME"
                                    SelectCommandType="StoredProcedure"
                                    OnSelecting="SqlDataSource_Lookup_Selecting">
                                    <SelectParameters>
                                    <asp:ControlParameter Name="ENG_ID_IN" Direction="Input" DefaultValue="0" DbType="Int32" ControlID="dropdown_PDCEngine" PropertyName="SelectedValue" />
                                    <asp:Parameter Name="USER_IN" Direction="Input" DefaultValue="DBG_USER" DbType="String" Size="255"/>
                                    <asp:Parameter Name="DEBUG_IN" Direction="Input" DefaultValue="0" DbType="Int32"/>
                                    <asp:Parameter Name="EXIT_CD_OUT" Direction="Output" DefaultValue="" DbType="Int32"/>
                                    <asp:Parameter Name="ERRMSG_OUT" Direction="Output" DefaultValue="" DbType="String" Size="255"/>
                                    <asp:Parameter Name="ERRCODE_OUT" Direction="Output" DefaultValue="" DbType="Int32"/>
                                    <asp:Parameter Name="ERRLINE_OUT" Direction="Output" DefaultValue="" DbType="String" Size="255"/>           
                                    <asp:SessionParameter Name="VALUES_OUT" Direction="Output" DefaultValue="" DbType="String" Size="255"/>
                                    </SelectParameters>
        </asp:SqlDataSource>
        <div class="breaker_portlet">&nbsp;</div> 
    </asp:Panel>
    <!-- inner portlet 3 Oracle table log  -->
</asp:Content>
