<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="AdminUserMngmt.aspx.cs" Inherits="PDC.AdminUserMngmt" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">

  <div class="PortletBoxInner">
  <p class="PDCPagingInfo"><asp:Label ID="PagingInformation" runat="server" Text=""></asp:Label>
        &nbsp;
        Number of rows per page:
        &nbsp;
        <asp:DropDownList 
                ID="PagerCountperPage" runat="server" AutoPostBack="True" 
                onselectedindexchanged="PagerCountperPage_SelectedIndexChanged">
				<asp:ListItem Enabled="false" Value="Dummy due to asp bug"/>
				<asp:ListItem Value="10"></asp:ListItem>
				<asp:ListItem>20</asp:ListItem>
				<asp:ListItem>30</asp:ListItem>
				<asp:ListItem>40</asp:ListItem>
				<asp:ListItem>50</asp:ListItem>
				<asp:ListItem>100</asp:ListItem>
				<asp:ListItem>200</asp:ListItem>
				<asp:ListItem>300</asp:ListItem>
				<asp:ListItem>400</asp:ListItem>
				<asp:ListItem>500</asp:ListItem>
            </asp:DropDownList>
        </p>
    <div class="scrollable"><asp:GridView ID="gv_UserList" runat="server" 
                DataSourceID="SqlDataSource_UserMngmt" AllowPaging="True"
             AllowSorting="True" AutoGenerateColumns="False"
            CellPadding="2" CellSpacing="1" GridLines="None" CssClass="PDCTbl" EmptyDataText="No rows"
             EnableViewState="False" DataKeyNames="USR_NAME"
            PagerSettings-Mode="NumericFirstLast" PagerSettings-Position="TopAndBottom" 
            ondatabound="gv_UserList_DataBound" AutoGenerateEditButton="True" 
            EditRowStyle-Width="100" AutoGenerateDeleteButton="True">

<PagerSettings Mode="NumericFirstLast" Position="TopAndBottom"></PagerSettings>

            <RowStyle CssClass="PDCTblRow" Wrap="False" />
            <SelectedRowStyle CssClass="PDCTblSelRow" />
            <SortedAscendingHeaderStyle CssClass="sort_asc" />
            <SortedDescendingHeaderStyle CssClass="sort_desc" />
            <AlternatingRowStyle CssClass="PDCTblEvenRow" />
            <HeaderStyle CssClass="PDCTblHeader" />
            <Columns>
                <asp:BoundField DataField="USR_NAME" HeaderText="USR_NAME" ReadOnly="true"/>

            <asp:TemplateField SortExpression="ACCESS_ROLE" HeaderText="ACCESS_ROLE" >
                    <EditItemTemplate>
                        <asp:DropDownList DataSourceID="SqlDataSource_LKP_GUI_ACCESS_ROLE" DataTextField="ACCESS_ROLE" DataValueField="ACCESS_ROLE" ID="DDListACCESS_ROLE" Runat="server" SelectedValue='<%# Bind("ACCESS_ROLE") %>' >
                    </asp:DropDownList>
                    </EditItemTemplate>
                    <ItemTemplate >
                        <asp:Label Runat="server" Text='<%# Bind("ACCESS_ROLE") %>' ID="ACCESS_ROLE"></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>


            </Columns>

            <EditRowStyle Width="100px"></EditRowStyle>
            <PagerStyle CssClass="PDCTblPaging" />
            <FooterStyle CssClass="PDCTblFooter" />
        </asp:GridView></div>
    <div class="breaker_portlet">&nbsp;</div> 
    </div>
    <div class="PortletBoxInner">
        <p>
            <span class="ModuleHeader">Create User</span>
            <br />
            Username:&nbsp;
            <asp:TextBox ID="tUsername" runat="server"></asp:TextBox>
            &nbsp;<asp:DropDownList DataSourceID="SqlDataSource_LKP_GUI_ACCESS_ROLE" DataTextField="ACCESS_ROLE" DataValueField="ACCESS_ROLE" ID="DDListADD_USER_ACCESS_ROLE" Runat="server" EnableViewState="False"></asp:DropDownList>
            
            
            
            <asp:RegularExpressionValidator ID="rexv1" CssClass="T4" runat="server" ErrorMessage="Not valid username (only chars and numbers)" ControlToValidate="tUsername" ValidationExpression="^[0-9a-zA-Z]{1,40}$"></asp:RegularExpressionValidator>
            
        </p>
            <div class="breaker_portlet">&nbsp;</div> 
            <asp:LinkButton ID="lbCMDNewUser" runat="server"  CommandName="COMMAND_NEW_USER" CommandArgument="true" OnCommand="BPDCCommandPressed" CssClass="PDCButton"><span>Create User</span></asp:LinkButton>
            <div class="breaker_portlet">&nbsp;</div> 

    </div>



    <asp:SqlDataSource ID="SqlDataSource_UserMngmt" runat="server" 

            ConnectionString="<%$ ConnectionStrings:PDCOracleConnection.connectionString %>"
            ProviderName="<%$ ConnectionStrings:PDCOracleConnection.ProviderName %>" EnableViewState="False" 
            SelectCommand="PCKG_GUI.SP_GUI_VIEW_USER_MNGMT" 
            SelectCommandType="StoredProcedure"
            onselected="SqlDataSource_UserMngmt_Selected" 
            onselecting="SqlDataSource_UserMngmt_Selecting"

            UpdateCommandType="StoredProcedure" 
            UpdateCommand="PCKG_GUI.SP_GUI_UPDT_USER_MNGMT" 
            onupdating="SqlDataSource_UserMngmt_Updating" 
            onupdated="SqlDataSource_UserMngmt_Updated"

            DeleteCommand="PCKG_GUI.SP_GUI_UPDT_USER_MNGMT_DEL"
            DeleteCommandType="StoredProcedure"
            OnDeleting="SqlDataSource_UserMngmt_Deleting"
            OnDeleted="SqlDataSource_UserMngmt_Deleted"

            >
             <SelectParameters>
                <asp:Parameter Name="USER_IN" Direction="Input" DefaultValue="DBG_USER" DbType="String" Size="255"/>
                <asp:Parameter Name="DEBUG_IN" Direction="Input" DefaultValue="0" DbType="String" />
                <asp:Parameter Name="EXIT_CD_OUT" Direction="Output" DbType="String" Size="255" />
                <asp:Parameter Name="ERRMSG_OUT" Direction="Output" DbType="String" Size="255" />
                <asp:Parameter Name="ERRCODE_OUT" Direction="Output" DbType="String" Size="255" />
                <asp:Parameter Name="ERRLINE_OUT" Direction="Output" DbType="String" Size="255" />

                <asp:SessionParameter Name="VALUES_OUT" Direction="Output" DefaultValue="" DbType="String" Size="255"/>

            </SelectParameters>

            <UpdateParameters>
    
               <asp:Parameter Name="USER_IN" Direction="Input" DefaultValue="DBG_USER" DbType="String" Size="255"/>
                <asp:Parameter Name="LOGIN_IN" Direction="Input" DefaultValue="DBG_USER" DbType="String" Size="255"/>
                <asp:ControlParameter ControlID="tUsername" Name="PASS_IN" PropertyName="Text" />
                <asp:Parameter Name="ACCESS_ROLE_IN" DefaultValue="DBG" Direction="Input" Type="String"  Size="255" />
             
                <asp:Parameter Name="DEBUG_IN" Direction="Input" DefaultValue="0" DbType="String" />
                <asp:Parameter Name="EXIT_CD_OUT" Direction="Output" DbType="String" Size="255" />
                <asp:Parameter Name="ERRMSG_OUT" Direction="Output" DbType="String" Size="255" />
                <asp:Parameter Name="ERRCODE_OUT" Direction="Output" DbType="String" Size="255" />
                <asp:Parameter Name="ERRLINE_OUT" Direction="Output" DbType="String" Size="255" />

            </UpdateParameters>
             <DeleteParameters>
    
               <asp:Parameter Name="USER_IN" Direction="Input" DefaultValue="DBG_USER" DbType="String" Size="255"/>
                <asp:Parameter Name="LOGIN_IN" Direction="Input" DefaultValue="DBG_USER" DbType="String" Size="255"/>
             
                <asp:Parameter Name="DEBUG_IN" Direction="Input" DefaultValue="0" DbType="String" />
                <asp:Parameter Name="EXIT_CD_OUT" Direction="Output" DbType="String" Size="255" />
                <asp:Parameter Name="ERRMSG_OUT" Direction="Output" DbType="String" Size="255" />
                <asp:Parameter Name="ERRCODE_OUT" Direction="Output" DbType="String" Size="255" />
                <asp:Parameter Name="ERRLINE_OUT" Direction="Output" DbType="String" Size="255" />

            </DeleteParameters>

        </asp:SqlDataSource>

                 <asp:SqlDataSource ID="SqlDataSource_LKP_GUI_ACCESS_ROLE" runat="server" 
            ConnectionString="<%$ ConnectionStrings:PDCOracleConnection.connectionString %>"
            ProviderName="<%$ ConnectionStrings:PDCOracleConnection.ProviderName %>" 
            EnableViewState="False"
            SelectCommand="select DISTINCT ACCESS_ROLE AS ACCESS_ROLE from LKP_GUI_ACCESS_ROLE order by ACCESS_ROLE">
        </asp:SqlDataSource>
 
</asp:Content>
