<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="AdminAccessControl.aspx.cs" Inherits="PDC.AdminAccessControl" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">

    <div class="PortletBoxInner">
        <p>
            <span class="ModuleHeader">Access Control Management</span>
            <br />
            Rowcount:&nbsp;<asp:Label ID="lDetailRowCount" runat="server" Text="-" EnableViewState="False"></asp:Label>
            <br />
            <asp:DropDownList DataSourceID="SqlDataSource_LKP_GUI_ACCESS_ROLE" DataTextField="ACCESS_ROLE" DataValueField="ACCESS_ROLE" ID="DDListACCESS_ROLE_MAIN" Runat="server" AppendDataBoundItems="true" AutoPostBack="true">
            <asp:ListItem>ALL</asp:ListItem>
            </asp:DropDownList>

        </p>
    </div>
    <!-- inner portlet 2 tab test  -->

    <asp:Panel ID="p_Detail_lvl1" runat="server" EnableViewState="False" CssClass="PortletBoxInner">
    
    
        <p class="PDCPagingInfo"><asp:Label ID="PagingInformation" runat="server" Text=""></asp:Label>
        &nbsp;
        Number of rows per page:
        &nbsp;
        <asp:DropDownList 
                ID="PagerCountperPage" runat="server" AutoPostBack="True" 
                onselectedindexchanged="PagerCountperPage_SelectedIndexChanged">
				<asp:ListItem Enabled="false" Value="Dummy due to asp bug"/>
				<asp:ListItem Value="10"></asp:ListItem>
				<asp:ListItem>20</asp:ListItem>
				<asp:ListItem>30</asp:ListItem>
				<asp:ListItem>40</asp:ListItem>
				<asp:ListItem>50</asp:ListItem>
				<asp:ListItem>100</asp:ListItem>
				<asp:ListItem>200</asp:ListItem>
				<asp:ListItem>300</asp:ListItem>
				<asp:ListItem>400</asp:ListItem>
				<asp:ListItem>500</asp:ListItem>
            </asp:DropDownList>
        </p>
        <div class="scrollable"><asp:GridView ID="GridView2" runat="server" 
                DataSourceID="SqlDataSource1" AllowPaging="True"
             AllowSorting="True" AutoGenerateColumns="False"
            CellPadding="2" CellSpacing="1" GridLines="None" CssClass="PDCTbl" EmptyDataText="No rows"
             EnableViewState="False" DataKeyNames="ACCESS_ROLE,GUI_PAGE,ACCESS_RIGHT"
            PagerSettings-Mode="NumericFirstLast" PagerSettings-Position="TopAndBottom" 
            ondatabound="GridView2_DataBound" AutoGenerateEditButton="True" 
            EditRowStyle-Width="100" AutoGenerateDeleteButton="True">

<PagerSettings Mode="NumericFirstLast" Position="TopAndBottom"></PagerSettings>

            <RowStyle CssClass="PDCTblRow" Wrap="False" />
            <SelectedRowStyle CssClass="PDCTblSelRow" />
            <SortedAscendingHeaderStyle CssClass="sort_asc" />
            <SortedDescendingHeaderStyle CssClass="sort_desc" />
            <AlternatingRowStyle CssClass="PDCTblEvenRow" />
            <HeaderStyle CssClass="PDCTblHeader" />
            <Columns>

                 <asp:TemplateField SortExpression="ACCESS_ROLE" HeaderText="ACCESS_ROLE" >
                    <EditItemTemplate>
                        <asp:DropDownList DataSourceID="SqlDataSource_LKP_GUI_ACCESS_ROLE" DataTextField="ACCESS_ROLE" DataValueField="ACCESS_ROLE" ID="DDListACCESS_ROLE" Runat="server" SelectedValue='<%# Bind("ACCESS_ROLE") %>' >
                    </asp:DropDownList>
                    </EditItemTemplate>
                    <ItemTemplate >
                        <asp:Label Runat="server" Text='<%# Bind("ACCESS_ROLE") %>' ID="ACCESS_ROLE"></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>


                 <asp:TemplateField SortExpression="GUI_PAGE" HeaderText="GUI_PAGE" >
                    <EditItemTemplate>
                        <asp:DropDownList DataSourceID="SqlDataSource_LKP_GUI_ACCESS_MENU" DataTextField="GUI_PAGE" DataValueField="GUI_PAGE" ID="DDListGUI_PAGE" Runat="server" SelectedValue='<%# Bind("GUI_PAGE") %>' >
                    </asp:DropDownList>
                    </EditItemTemplate>
                    <ItemTemplate >
                        <asp:Label Runat="server" Text='<%# Bind("GUI_PAGE") %>' ID="GUI_PAGE"></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>


                 <asp:TemplateField SortExpression="ACCESS_RIGHT" HeaderText="ACCESS_RIGHT" >
                    <EditItemTemplate>
                        <asp:DropDownList DataSourceID="SqlDataSource_LKP_GUI_ACCESS_CONTROL" DataTextField="ACCESS_RIGHT" DataValueField="ACCESS_RIGHT" ID="DDListACCESS_RIGHT" Runat="server" SelectedValue='<%# Bind("ACCESS_RIGHT") %>' >
                    </asp:DropDownList>
                    </EditItemTemplate>
                    <ItemTemplate >
                        <asp:Label Runat="server" Text='<%# Bind("ACCESS_RIGHT") %>' ID="ACCESS_RIGHT"></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
            </Columns>

            <EditRowStyle Width="100px"></EditRowStyle>
            <PagerStyle CssClass="PDCTblPaging" />
            <FooterStyle CssClass="PDCTblFooter" />
        </asp:GridView></div>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
            onselected="SqlDataSource_Selected" 
            onselecting="SqlDataSource_Selecting"
            ConnectionString="<%$ ConnectionStrings:PDCOracleConnection.connectionString %>"
            ProviderName="<%$ ConnectionStrings:PDCOracleConnection.ProviderName %>" EnableViewState="False" 
            SelectCommand="PCKG_GUI.SP_GUI_VIEW_ACCESS_ROLE" 
            SelectCommandType="StoredProcedure"

            UpdateCommandType="StoredProcedure" 
            UpdateCommand="PCKG_GUI.SP_GUI_UPDT_ACCESS_ROLE" 
            onupdating="SqlDataSource_Updating" onupdated="SqlDataSource_Updated"

            DeleteCommand="PCKG_GUI.SP_GUI_UPDT_ACCESS_ROLE_DEL"
            DeleteCommandType="StoredProcedure"
            OnDeleting="SqlDataSource_Deleting"
            OnDeleted="SqlDataSource_Deleted"

            >
             <SelectParameters>
                     
            <asp:ControlParameter Name="ENG_ID_IN" Direction="Input" DefaultValue="0" DbType="String" Size="255" ControlID="dropdown_PDCEngine" PropertyName="SelectedValue" />
            <asp:Parameter Name="USER_IN" Direction="Input" DefaultValue="DBG_USER" DbType="String" Size="255"/>
            <asp:Parameter Name="DEBUG_IN" Direction="Input" DefaultValue="0" DbType="String" Size="255"/>
            <asp:Parameter Name="EXIT_CD_OUT" Direction="Output" DefaultValue="" DbType="String" Size="255"/>
            <asp:Parameter Name="ERRMSG_OUT" Direction="Output" DefaultValue="" DbType="String" Size="255"/>
            <asp:Parameter Name="ERRCODE_OUT" Direction="Output" DefaultValue="" DbType="String" Size="255"/>
            <asp:Parameter Name="ERRLINE_OUT" Direction="Output" DefaultValue="" DbType="String" Size="255"/>
            <asp:ControlParameter Name="ACCESS_ROLE_IN" Direction="Input" DefaultValue="ALL" DbType="String" Size="255" ControlID="DDListACCESS_ROLE_MAIN" PropertyName="SelectedValue"/>
            <asp:SessionParameter Name="VALUES_OUT" Direction="Output" DefaultValue="" DbType="String" Size="255"/>

        </SelectParameters>
            <UpdateParameters>
    
              <asp:ControlParameter Name="ENG_ID_IN" Direction="Input" DefaultValue="0" DbType="String" Size="255" ControlID="dropdown_PDCEngine" PropertyName="SelectedValue" />
            <asp:Parameter Name="USER_IN" Direction="Input" DefaultValue="DBG_USER" DbType="String" Size="255"/>
             
                <asp:Parameter Name="DEBUG_IN" Direction="Input" DefaultValue="0" DbType="String" />
                <asp:Parameter Name="EXIT_CD_OUT" Direction="Output" DbType="String" Size="255" />
                <asp:Parameter Name="ERRMSG_OUT" Direction="Output" DbType="String" Size="255" />
                <asp:Parameter Name="ERRCODE_OUT" Direction="Output" DbType="String" Size="255" />
                <asp:Parameter Name="ERRLINE_OUT" Direction="Output" DbType="String" Size="255" />

                <asp:Parameter Name="ACCESS_ROLE_IN" DefaultValue="DBG" Direction="Input" Type="String"  Size="255" />
                <asp:Parameter Name="GUI_PAGE_IN" DefaultValue="DBG" Direction="Input" Type="String"  Size="255" />
                <asp:Parameter Name="ACCESS_RIGHT_IN" DefaultValue="DBG" Direction="Input" Type="String"  Size="255" />

            </UpdateParameters>

        </asp:SqlDataSource>

         <asp:SqlDataSource ID="SqlDataSource_LKP_GUI_ACCESS_ROLE" runat="server" 
            ConnectionString="<%$ ConnectionStrings:PDCOracleConnection.connectionString %>"
            ProviderName="<%$ ConnectionStrings:PDCOracleConnection.ProviderName %>" 
            EnableViewState="False"
            SelectCommand="select DISTINCT ACCESS_ROLE AS ACCESS_ROLE from LKP_GUI_ACCESS_ROLE order by ACCESS_ROLE">
        </asp:SqlDataSource>
         <asp:SqlDataSource ID="SqlDataSource_LKP_GUI_ACCESS_CONTROL" runat="server" 
            ConnectionString="<%$ ConnectionStrings:PDCOracleConnection.connectionString %>"
            ProviderName="<%$ ConnectionStrings:PDCOracleConnection.ProviderName %>" 
            EnableViewState="False"
            SelectCommand="select ACCESS_RIGHT AS ACCESS_RIGHT from LKP_GUI_ACCESS_CONTROL order by ACCESS_RIGHT">
        </asp:SqlDataSource>
          <asp:SqlDataSource ID="SqlDataSource_LKP_GUI_ACCESS_MENU" runat="server" 
            ConnectionString="<%$ ConnectionStrings:PDCOracleConnection.connectionString %>"
            ProviderName="<%$ ConnectionStrings:PDCOracleConnection.ProviderName %>" 
            EnableViewState="False"
            SelectCommand="select ACCESS_MENU AS GUI_PAGE from LKP_GUI_ACCESS_MENU order by ACCESS_MENU">
        </asp:SqlDataSource>

        <div class="breaker_portlet">&nbsp;</div> 
    </asp:Panel>
    <!-- inner portlet 3 Oracle table log  -->

       <div class="PortletBoxInner">
        <p>
            <span class="ModuleHeader">Add</span>
            <br />
                <asp:DropDownList DataSourceID="SqlDataSource_LKP_GUI_ACCESS_ROLE" DataTextField="ACCESS_ROLE" DataValueField="ACCESS_ROLE" ID="DDListADD_ACCESS_ROLE" Runat="server" EnableViewState="False">
                </asp:DropDownList>

                <asp:DropDownList DataSourceID="SqlDataSource_LKP_GUI_ACCESS_MENU" DataTextField="GUI_PAGE" DataValueField="GUI_PAGE" ID="DDListADD_GUI_PAGE" Runat="server"  EnableViewState="False">
                </asp:DropDownList>

                <asp:DropDownList DataSourceID="SqlDataSource_LKP_GUI_ACCESS_CONTROL" DataTextField="ACCESS_RIGHT" DataValueField="ACCESS_RIGHT" ID="DDListADD_ACCESS_RIGHT" Runat="server"  EnableViewState="False">
                </asp:DropDownList>

        </p>
           <asp:Panel ID="Panel1" runat="server"  EnableViewState="False">
                <asp:LinkButton ID="lbCMDNewRole" runat="server"  CommandName="COMMAND_NEW_ROLE" CommandArgument="true" OnCommand="BPDCCommandPressed" CssClass="PDCButton"><span>Add Relation</span></asp:LinkButton>
            </asp:Panel>
        <div class="breaker_portlet">&nbsp;</div> 
    </div>

  

</asp:Content>
