--rozsireni lookupu
INSERT INTO "PDC"."LKP_JOB_TYPE" (JOB_TYPE) VALUES ('INFORMATICA_NOWAIT');

--stavajici joby u kterych ma dojit ke zmene job_typu
UPDATE CTRL_JOB
SET JOB_TYPE='INFORMATICA_NOWAIT'
WHERE JOB_NAME IN ('GDW_WF_STATISTICS_CMD_FINISHED',
'GDW_WF_STATISTICS_S_MP_STA_PROC_STATS_EXEC_SEQ1',
'GDW_WF_STATISTICS_S_MP_STA_PROC_STATS_EXEC_SEQ2',
'GDW_WF_STATISTICS_S_MP_STA_PROC_STATS_INIT_SEQ1',
'GDW_WF_STATISTICS_S_MP_STA_PROC_STATS_INIT_SEQ2');